query PostBySlug($slug: String!, $lang: String!) {
  postConnection(filter: { slug: { eq: $slug }, language: { eq: $lang } }) {
    edges {
      node {
        ...PostMeta
        id
        title
        description
        publishedAt: published_at
        modifiedAt: modified_at
        body
        tags {
          tag {
            ... on Tag {
              name
            }
          }
        }
        _sys {
          path
        }
      }
    }
  }
}

query TranslationBySlug($slug: String!) {
  allTranslationMetadata: translation_metadataConnection(
    filter: { translations: { value: { post: { slug: { eq: $slug } } } } }
  ) {
    edges {
      node {
        translations {
          value {
            ... on Post {
              slug
              language
            }
          }
        }
      }
    }
  }
}

query AllPosts {
  postConnection {
    edges {
      node {
        slug
        language
        _sys {
          path
          filename
          title
          basename
          hasReferences
          breadcrumbs
          relativePath
          extension
        }
      }
    }
  }
}
