on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            prod: false

    environment:
      name: ${{ matrix.environment }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - run: deno install

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          path: dist

      - name: Upload Version
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload --name ${{ vars.WORKER_NAME }}

      - name: Get Latest Version ID
        id: version_list
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions list --name ${{ vars.WORKER_NAME }} --json

      - name: Parse Id
        id: list_parser
        run: echo "id=${{ fromJson(steps.version_list.outputs.command-output)[0].id }}" >> $GITHUB_OUTPUT

      - name: Debug
        run: echo ${{ steps.list_parser.outputs.id }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions deploy ${{ steps.list_parser.outputs.id }}@100%
