on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            prod: false

    environment:
      name: ${{ matrix.environment }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - run: deno install

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          path: dist

      - name: Upload Version
        id: upload_version
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload --name ${{ vars.WORKER_NAME }}

      - name: Debug
        run: echo ${{ fromJSON(steps.upload_version.outputs.command-output).id }}

      - name: Parse Version ID
        id: parse
        run: echo "id=${{ fromJSON(steps.upload_version.outputs.command-output).id }}" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions deploy ${{ steps.parse.outputs.id }}@100%
